=== bjornmartensson/ictk/src/main/java/ictk/boardgame/chess/net/ics/event/icsevtml.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
 * ictk - Internet Chess ToolKit
 * More information is available at http://jvarsoke.github.io/ictk
 * Copyright (c) 1997-2014 J. Varsoke <ictk.jvarsoke [at] neverbox.com>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
-->
<!ELEMENT icsevtml (event*, class*, interface*, membertype*)>
<!ATTLIST icsevtml
	  xmlns:icsevt	CDATA		"http://ictk.sourceforge.net/ics/evt"
	  >

<!ELEMENT event (description?, 
                 statics*,
		 implements*,
		 member*,
		 code?,
		 parser+)>
<!ATTLIST event
          id		ID		#REQUIRED
	  class		NMTOKEN		#REQUIRED
	  enum		NMTOKEN		#REQUIRED
	  extends	IDREF 		"ICSEvent"
	  >

<!ELEMENT description (#PCDATA)*>
<!ATTLIST description
	  xml:space	(default | preserve)	'preserve'
	  >

<!ELEMENT statics (#PCDATA)*>
<!ATTLIST statics 
	  format	NOTATION (java)	#REQUIRED
	  xml:space	(default | preserve)	'preserve'
	  >


<!ELEMENT implements EMPTY>
<!ATTLIST implements
	  idref		IDREF		#REQUIRED
	  >

<!ELEMENT member EMPTY>
<!ATTLIST member 
	  id		ID		#REQUIRED
	  typeref	IDREF		#REQUIRED
	  varname	NMTOKEN		#IMPLIED
	  functname	NMTOKEN		#IMPLIED
	  exactfunctname (no | yes)	"no"
	  inherit	(both | member | method | none)	"none"
	  >

<!ELEMENT parser (description?, regex+, assignMatches, toNative)>
<!ATTLIST parser
	  id		ID		#REQUIRED
	  name		NMTOKEN		#REQUIRED
	  enum          NMTOKEN		#IMPLIED
	  protocol	(FICS | ICC)	#REQUIRED
	  extends	NMTOKEN		"ICSEventParser"
	  detectFake	(yes | no)	"yes"
	  >

<!ELEMENT regex (#PCDATA | regexref)*>
<!ATTLIST regex
	  id		ID		#IMPLIED
	  >

<!ELEMENT regexref EMPTY>
<!ATTLIST regexref
	  ref		IDREF		#REQUIRED
	  >

<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	  format	NOTATION (java)	#REQUIRED
	  xml:space	(default | preserve)	'preserve'
	  >
<!NOTATION java		SYSTEM "http://java.sun.com"> <!-- ? -->

<!ELEMENT assignMatches (#PCDATA | attr)*>
<!ATTLIST assignMatches
	  format	NOTATION (java) #REQUIRED
	  >

<!ELEMENT toNative (code+)>
<!ATTLIST toNative
	  avgLength	NMTOKEN		#REQUIRED
	  >

<!--membertypes -->

<!ELEMENT membertype (regex*)>
<!ATTLIST membertype
	  id		ID		#REQUIRED
	  type		NMTOKEN		#REQUIRED
	  varname	NMTOKEN		#REQUIRED
	  functname	NMTOKEN		#REQUIRED
	  >

<!ELEMENT class EMPTY>
<!ATTLIST class
          id		ID		#REQUIRED
	  type		NMTOKEN		#REQUIRED
	  >

<!ELEMENT interface (attributes*, method*)>
<!ATTLIST interface
	  id		ID		#REQUIRED
	  type		NMTOKEN		#REQUIRED
	  >
<!ELEMENT method (code+)>

=== bjornmartensson/ictk/src/main/java/ictk/boardgame/chess/net/ics/event/seekRemove.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--
 * ictk - Internet Chess ToolKit
 * More information is available at http://jvarsoke.github.io/ictk
 * Copyright (c) 1997-2014 J. Varsoke <ictk.jvarsoke [at] neverbox.com>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
-->
<!DOCTYPE icsevtml SYSTEM "icsevtml.dtd" [
   <!ENTITY common SYSTEM "parserCommon.xml">
   ]>

<icsevtml>
   <!-- channel............................................................-->
   <event id="seekRemove" 
          class="SeekRemove"
	  enum="SEEK_REMOVE"
	  >

      <description>
         This message from the server indicates that a number of
	 seek ads should be cleared from the client's records.  The server
	 does not keep track of which seeks you know about though.
      </description>

      <member id="seekRemove:ads"	typeref="int[]"
              varname="ads"
	      functname="Ads"
	      />

      <!--pin parser-->
      <parser id="seekRemove:parser"
              name="SeekRemove"
              protocol="FICS"
              extends="ICSEventParser"
	      detectFake="no">

         <!-- regex -->
	 <regex>
	    &lt;sr>
	    ((?:\s\d+)+) <!-- multiple numbers to remove -->
	 </regex>

         <!-- assignMatches -->
	 <assignMatches format="java">
      StringTokenizer st = new StringTokenizer(m.group(2));

      int[] ads = new int[st.countTokens()];
      int i = 0;
      try {
         while (st.hasMoreTokens()) {
	    ads[i] = Integer.parseInt(st.nextToken());
	    i++;
	 }
      }
      catch (NumberFormatException e) {
         Log.error(Log.PROG_WARNING,
            "Can't parse ads[" + i + "] "
            + "of " + m.group(0));
         evt.setEventType(ICSEvent.UNKNOWN_EVENT);
         evt.setMessage(m.group(0));
         if (Log.debug)
            Log.debug(ICSEventParser.DEBUG, "regex", m);
         return;
      }
      evt.setAds(ads);
	 </assignMatches>

         <!-- toNative -->
         <toNative avgLength="5">
	    <code format="java">
      int[] ads = evt.getAds();
      sb.append("&lt;sr>");
      for (int i=0; i &lt; ads.length; i++)
         sb.append(" ")
	   .append(ads[i]);
	    </code>
	 </toNative>
      </parser>
   </event>
   &common;
</icsevtml>

=== bjornmartensson/ictk/src/main/java/ictk/boardgame/chess/net/ics/event/tell.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--
 * ictk - Internet Chess ToolKit
 * More information is available at http://jvarsoke.github.io/ictk
 * Copyright (c) 1997-2014 J. Varsoke <ictk.jvarsoke [at] neverbox.com>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
-->
<!DOCTYPE ictkml SYSTEM "icsevtml.dtd" [
   <!ENTITY common SYSTEM "parserCommon.xml">
   ]>

<icsevtml>
   <!-- tell event ........................................................-->
   <event id="tell" 
          class="Tell"
	  enum="TELL"
	  extends="ICSMessageEvent">

      <description>
         Direct tells to the user through "tell" or "say".
      </description>

      <member id="tell:player"      typeref="player"/>
      <member id="tell:accountType" typeref="accountType"/>
      <member id="tell:message"     typeref="message"     inherit="yes"/>

      <!--parser-->
      <parser id="tell:parser"
              name="Tell"
              protocol="FICS"
              extends="ICSEventParser"
	      detectFake="yes">

         <!-- regex -->
	 <regex>
	    <regexref ref="regex:fics:player"/>
	    <regexref ref="regex:fics:accountType"/>
	    \s(tells\syou|says):\s
	    <regexref ref="regex:fics:message"/>
	 </regex>

         <!-- assignMatches -->
	 <assignMatches format="java">
	    <regexgroup num="2" memberref="tell:player"/>
	    <regexgroup num="3" memberref="tell:accountType"/>
	    <regexgroup num="5" memberref="tell:message"/>
      if ("tells you".equals(m.group(4))) {
         evt.setEventType(ICSEvent.TELL_EVENT);
      }
      else if ("says".equals(m.group(4))) {
         evt.setEventType(ICSEvent.SAY_EVENT);
      }
	 </assignMatches>

         <!-- toNative -->
         <toNative avgLength="20">
	    <code format="java">
      sb.append(evt.getPlayer())
        .append(evt.getAccountType());

      switch (evt.getEventType()) {
         case ICSEvent.TELL_EVENT:
            sb.append(" tells you: ");
            break;

         case ICSEvent.SAY_EVENT:
            sb.append(" says: ");
            break;
      }

      sb.append(evt.getMessage());
	    </code>

	 </toNative>
      </parser>
   </event>
   &common;
</icsevtml>

=== bjornmartensson/ictk/src/main/java/ictk/boardgame/chess/net/ics/event/seekClear.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--
 * ictk - Internet Chess ToolKit
 * More information is available at http://jvarsoke.github.io/ictk
 * Copyright (c) 1997-2014 J. Varsoke <ictk.jvarsoke [at] neverbox.com>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
-->
<!DOCTYPE icsevtml SYSTEM "icsevtml.dtd" [
   <!ENTITY common SYSTEM "parserCommon.xml">
   ]>

<icsevtml>
   <!-- channel............................................................-->
   <event id="seekClear" 
          class="SeekClear"
	  enum="SEEK_CLEAR"
	  >

      <description>
         This message from the server indicates that all known seeks
	 should be cleared.
      </description>

      <!--pin parser-->
      <parser id="seekClear:parser"
              name="SeekClear"
              protocol="FICS"
              extends="ICSEventParser"
	      detectFake="no">

         <!-- regex -->
	 <regex>
	    &lt;
	    sc>  <!-- 'n' means does not meet formula -->
	 </regex>

         <!-- assignMatches -->
	 <assignMatches format="java">
      //nothing to do
	 </assignMatches>

         <!-- toNative -->
         <toNative avgLength="5">
	    <code format="java">
      sb.append("&lt;sc>");
	    </code>
	 </toNative>
      </parser>
   </event>
   &common;
</icsevtml>

=== bjornmartensson/ictk/src/main/java/ictk/boardgame/chess/net/ics/event/playerConnection.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--
 * ictk - Internet Chess ToolKit
 * More information is available at http://jvarsoke.github.io/ictk
 * Copyright (c) 1997-2014 J. Varsoke <ictk.jvarsoke [at] neverbox.com>
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
-->
<!DOCTYPE icsevtml SYSTEM "icsevtml.dtd" [
   <!ENTITY common SYSTEM "parserCommon.xml">
   ]>

<icsevtml>
   <!-- channel............................................................-->
   <event id="pcon" 
          class="PlayerConnection"
	  enum="PLAYER_CONNECTION"
	  >

      <description>
         This coorisponds to Player connection notification, either by
	 "pin=1" or someone on your Notify list.
      </description>

      <member id="pcon:player"      typeref="player"/>
      <member id="pcon:accountType" typeref="accountType"/>
      <member id="pcon:connected"   typeref="boolean"
              varname="connected"
	      functname="Connected"
              />
      <member id="pcon:notified"   typeref="boolean"
              varname="notified"
	      functname="Notification"
              />
      <member id="pcon:onNotifyList"   typeref="boolean"
              varname="onNotifyList"
	      functname="OnNotifyList"
              />


      <!--pin parser-->
      <parser id="pcon:pinparser"
              name="PlayerConnection"
              protocol="FICS"
              extends="ICSEventParser"
	      detectFake="no">

         <!-- regex -->
	 <regex>
	    \[
	    <regexref ref="regex:fics:player"/>
	    \shas\s
	    (connected|disconnected)
	    \.\]
	 </regex>

         <!-- assignMatches -->
	 <assignMatches format="java">
	    <regexgroup num="2" memberref="pcon:player"/>
      evt.setConnected("connected".equals(m.group(3)));
      evt.setNotification(false);
	 </assignMatches>

         <!-- toNative -->
         <toNative avgLength="50">
	    <code format="java">
      sb.append("[")
        .append(evt.getPlayer())
        .append(" has ");
      if (evt.isConnected())
         sb.append("connected");
      else
         sb.append("disconnected");
      sb.append(".]");
	    </code>
	 </toNative>
      </parser>

      <!--notification parser-->
      <parser id="pcon:notifcationparser"
              name="PlayerNotification"
	      enum="PLAYER_NOTIFICATION"
              protocol="FICS"
              extends="ICSEventParser"
	      detectFake="yes">

         <!-- regex -->
	 <regex>
	    Notification:\s
	    <regexref ref="regex:fics:player"/>
	    <regexref ref="regex:fics:accountType"/>
	    \shas\s
	    (arrived|departed)
	    (\sand\sisn't\son\syour\snotify\slist)?
	    \.
	 </regex>

         <!-- assignMatches -->
	 <assignMatches format="java">
	    <regexgroup num="2" memberref="pcon:player"/>
	    <regexgroup num="3" memberref="pcon:accountType"/>
      evt.setConnected("arrived".equals(m.group(4)));
      evt.setNotification(true);
      evt.setOnNotifyList(m.group(5) != null);
      evt.setEventType(ICSEvent.PLAYER_NOTIFICATION_EVENT);
	 </assignMatches>

         <!-- toNative -->
         <toNative avgLength="40">
	    <code format="java">
      sb.append("Notification: ")
        .append(evt.getPlayer())
        .append(evt.getAccountType())
        .append(" has ");

      if (evt.isConnected())
         sb.append("arrived");
      else
         sb.append("departed");

      if (evt.isOnNotifyList())
         sb.append(" and isn't on your notify list");

      sb.append(".");
	    </code>
	 </toNative>
      </parser>
   </event>
   &common;
</icsevtml>
